name: 'Pull Request'

on:
    pull_request:
        branches: [master]

jobs:
    commitlint:
        name: 'CommitLint'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    path: .
            -   uses: actions/setup-node@v2
                with:
                    node-version: 12
            -   run: echo "::set-output name=dir::$(yarn cache dir)"
                id: yarn-cache-dir
            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: yarn-cache-12-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: yarn-cache-12-
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/commitlint.sh

    eslint:
        name: 'ESLint'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    path: .
            -   uses: actions/setup-node@v2
                with:
                    node-version: 12
            -   run: echo "::set-output name=dir::$(yarn cache dir)"
                id: yarn-cache-dir
            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: yarn-cache-12-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: yarn-cache-12-
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/eslint.sh

    build_website:
        name: 'Website'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    path: .
            -   uses: actions/setup-node@v2
                with:
                    node-version: 12
            -   run: echo "::set-output name=dir::$(yarn cache dir)"
                id: yarn-cache-dir
            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: yarn-cache-12-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: yarn-cache-12-
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/build_website.sh

