name: 'Pull Request'

on:
    pull_request:
        branches: [master]

jobs:
    commitlint:
        name: 'CommitLint'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    path: .
            -   uses: actions/setup-node@v1
                with:
                    node-version: 12.x
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/commitlint.sh

    eslint:
        name: 'ESLint'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    path: .
            -   uses: actions/setup-node@v1
                with:
                    node-version: 12.x
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/eslint.sh

    build_website:
        name: 'Website'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    path: .
            -   uses: actions/setup-node@v1
                with:
                    node-version: 12.x
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/build_website.sh

