name: 'Puppeteer'

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test_puppeteer_chromium:
        name: 'Chromium'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    path: .
            -   uses: actions/setup-node@v2
                with:
                    node-version: 12
            -   run: echo "::set-output name=dir::$(yarn cache dir)"
                id: yarn-cache-dir
            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: yarn-cache-12-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: yarn-cache-12-
            -   run: bash ./scripts/ci/setup/default.sh
                env:
                    PUPPETEER_PRODUCT: chrome
            -   run: bash ./scripts/ci/setup/chromium.sh
            -   run: bash ./scripts/ci/jobs/test_puppeteer_chromium.sh
                env:
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            -   uses: actions/upload-artifact@v2
                if: ${{ failure() }}
                with:
                    name: screenshots_puppeteer_chromium
                    path: __artifacts__/jest/*.png
