name: 'Release'

on:
    push:
        branches: [master]

jobs:
    commitlint:
        name: 'CommitLint'
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
                with:
                    path: .
            -   uses: actions/setup-node@v3
                with:
                    node-version: 12
            -   run: echo "::set-output name=dir::$(yarn cache dir)"
                id: yarn-cache-dir
            -   uses: actions/cache@v2
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: yarn-cache-12-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: yarn-cache-12-
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/commitlint.sh

    deploy_website:
        name: 'Website'
        runs-on: ubuntu-latest
        needs: [commitlint]

        steps:
            -   uses: actions/checkout@v3
                with:
                    path: .
            -   uses: actions/setup-node@v3
                with:
                    node-version: 12
            -   run: echo "::set-output name=dir::$(yarn cache dir)"
                id: yarn-cache-dir
            -   uses: actions/cache@v2
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: yarn-cache-12-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: yarn-cache-12-
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/deploy_website.sh

    release_packages:
        name: 'Packages'
        runs-on: ubuntu-latest
        needs: [commitlint]

        steps:
            -   uses: actions/checkout@v3
                with:
                    path: .
            -   uses: actions/setup-node@v3
                with:
                    node-version: 12
            -   run: echo "::set-output name=dir::$(yarn cache dir)"
                id: yarn-cache-dir
            -   uses: actions/cache@v2
                with:
                    path: ${{ steps.yarn-cache-dir.outputs.dir }}
                    key: yarn-cache-12-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: yarn-cache-12-
            -   run: bash ./scripts/ci/setup/default.sh
            -   run: bash ./scripts/ci/jobs/release_packages.sh
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
